### ISSUE TITLE
Refactor classes to `cc.polyfrost.oneconfig.v0`

### ISSUE THREAD

**Issue by Wyvest** [Polyfrost/OneConfig#110]
If / when a redesign is done, it will most likely change the UX for both the user and the developer massively. Thus, to prepare for breaking API changes, we should move all current API to `cc.polyfrost.oneconfig.v0` excluding internal classes to mitigate issues with breaking changes.

Additionally, all PRs should be merged before this refactor as this will cause major merge conflicts.

**Comment by DeDiamondPro** [comment]
With refactor also move as many things to internal as possible

**Comment by nxtdaydelivery** [comment]
moved
