### ISSUE TITLE
MC turns black after enabling blur 

### ISSUE THREAD

**Issue by SrabonKhan0461** [Polyfrost/OneConfig#153]
### Bug description

Ok so IDK if you guys are aware of this but when I enable blur in oneconfig my mc just turns black but when I disable the blur ( by clicking on the place it was in since the screen is still black) it becomes normal again. Here's a few screenshots of before and after enabling the blur

[https://imgur.com/Jqwp1lQ](url)

[https://imgur.com/6YcCMno](url)

### Steps to reproduce

1. Open OneConfig GUI
2. Go to Preferences
3. Click on enable blur

### Expected behavior

it should just enable blur?

**Comment by Wyvest** [comment]
Go to https://discord.gg/polyfrost for support. This shouldn't happen lol

**Comment by SrabonKhan0461** [comment]
> Go to https://discord.gg/polyfrost for support. This shouldn't happen lol

ig its just a issue on myside i thought it was a bug lol
