### ISSUE TITLE
When entering the hud editor, clicking the little square makes it disappear, and impossible to get back.

### ISSUE THREAD

**Issue by electron271** [Polyfrost/OneConfig#159]
### Bug description

If you enter the HUD editor, clicking the little square makes the HUD element dissapear, and is impossible to get back.

### Steps to reproduce

1. Enter HUD editor
2. Grab some HUD object (tested with evergreenhud)
3. Click the little square
4. It dissapears.

**Comment by xtrm-en** [comment]
This should be fixed by now, asking confirmation @Wyvest
