### ISSUE TITLE
OneKeyBind doesn't support mouse bindings

### ISSUE THREAD

**Issue by pauliesnug** [Polyfrost/OneConfig#160]

**Comment by nxtdaydelivery** [comment]
fixed as of #162

**Comment by Wyvest** [comment]
Still doesn't work with mouse bindings, reopening issue.

**Comment by yodaluca23** [comment]
Any updates on this?

**Comment by yodaluca23** [comment]
The update today or yesterday fixed it! 😁

**Comment by pauliesnug** [comment]
> The update today or yesterday fixed it! 😁

@yodaluca23 yes, we merged #259 into the main release branch so it should be fixed for everyone
