### ISSUE TITLE
Dynamic config values

### ISSUE THREAD

**Issue by kingstefan26** [Polyfrost/OneConfig#164]
## Why
currently, there are no ways to create fields and associated config options on runtime without class reloading,  
the current annotation design is simple and well put together, but it breaks down when the project gets big. You end up with a massive class and all of your code ties back to one class
## Why not
I can't really think how this would affect other parts of the code base in a meaningfully bad way, it would definitely be a advanced feature not intended for simple small mods
## How it would look
I propose a api that would bypass the annotation part, and allow the dev to manually register an option, and retrieve its value. Something like `config.registerOption(id, new Slider(min, max, name, category))` and then `config.getOptionValue(id)`

**Comment by Wyvest** [comment]
@nextdayy Would this be possible in V1? I assume so, right?

**Comment by Wyvest** [comment]
It is possible in V1.
