### ISSUE TITLE
Multi choice settings

### ISSUE THREAD

**Issue by kingstefan26** [Polyfrost/OneConfig#165]
Currently, we only have dropdowns to chose among many exclusive states, I propose a option that would look like the `dual option` but have multiple options, with reflection magic it would be possible to choose one a emum value out of enum class, but that would require lot of work for little developer convenience
Dual option for reference:
![image](https://user-images.githubusercontent.com/70776766/200708054-5dd3f4de-c5f6-42b3-ad57-5f6ce4038108.png)

**Comment by kingstefan26** [comment]
Let this issue track the feature's progress?

**Comment by xtrm-en** [comment]
Tracking here: #226

**Comment by Wyvest** [comment]
Will be added in OneConfig V1, closing as this is a major feature request that is being addressed in other repos
