### ISSUE TITLE
Make `NanoVGHelper#drawImage` prepend "/" to images

### ISSUE THREAD

**Issue by Wyvest** [Polyfrost/OneConfig#192]
### Bug description

Currently, NanoVGHelper's drawImage function does not add "/" to the beginning of text. This causes NanoVG to not be able to find assets.

### Steps to reproduce

1. call `NanoVGHelper.INSTANCE.drawImage`

### Expected behavior

NanoVGHelper should automatically prepand "/" to images if they do not have a "/"

**Comment by xtrm-en** [comment]
This is expected behavior as per the [JVM Technotes](https://docs.oracle.com/javase/8/docs/technotes/guides/lang/resources.html#res_name_context)
