### ISSUE TITLE
Clarify License terms outside the LICENSE file

### ISSUE THREAD

**Issue by moehreag** [Polyfrost/OneConfig#232]
Currently, the License terms include the condition to have this text in a visible (and focused) area of the screen when using this library.
```
"Powered by OneConfig - get OneConfig from the original creators 
at <https://polyfrost.cc/oneconfig>"
```

In my opinion, this should already be clarified in the readme or the documentation to prevent License infringements later onwards since many people are unlikely to ever read to the bottom of the License file.

**Comment by Wyvest** [comment]
> Currently, the License terms include the condition to have this text in a visible (and focused) area of the screen when using this library.
> 
> ```
> "Powered by OneConfig - get OneConfig from the original creators 
> at <https://polyfrost.cc/oneconfig>"
> ```
> 
> In my opinion, this should already be clarified in the readme or the documentation to prevent License infringements later onwards since many people are unlikely to ever read to the bottom of the License file.

that only applies if they're making a modified version of OneConfig (an "Adaptation" in the license) and that's a pretty niche case
