### ISSUE TITLE
Icon on ign

### ISSUE THREAD

**Issue by catvin82** [Polyfrost/OneConfig#253]
## Is your feature request related to a problem? Please describe
No, But it would be nice to have an icon showing who is using oneconfig ingame.

## Describe the behaviour you'd like
just an icon, like lunar's, badlion's, essential's, labymod, or axolotlclient on the ign and tab menu showing that a person is using oneconfig.

## Describe alternatives you've considered
...

## Additional context
...

**Comment by TheKodeToad** [comment]
I don't know the opinions of the team, but this seems unlikely.

**Comment by catvin82** [comment]
ok
