### ISSUE TITLE
Notifications do not animate on first notification

### ISSUE THREAD

**Issue by badjavadev** [Polyfrost/OneConfig#265]
### Bug description

no animation on first notification

### Steps to reproduce

`Notifications.INSTANCE.send("Test", "Message");`

### Expected behavior

same animation on all notifications

**Comment by TheKodeToad** [comment]
i think it'd be better for oneconfig to have a mobile app and notifications to be sent through it instead!

**Comment by Wyvest** [comment]
> i think it'd be better for oneconfig to have a mobile app and notifications to be sent through it instead!

??

**Comment by TheKodeToad** [comment]
xD

**Comment by Wyvest** [comment]
Will be added in OneConfig V1, closing as this is a major feature request that is being addressed in other repos
