### ISSUE TITLE
The screen goes all white when I open the config menu

### ISSUE THREAD

**Issue by Ullerman** [Polyfrost/OneConfig#267]
### Bug description

[https://clipchamp.com/watch/hPAKxs57GZx](url)
![image](https://github.com/Polyfrost/OneConfig/assets/69403301/adbf7f8d-036b-4385-9a5c-dc27fe2b3218)
![image](https://github.com/Polyfrost/OneConfig/assets/69403301/84662c1f-0ba0-4c00-bfa3-b23e1804df04)
![image](https://github.com/Polyfrost/OneConfig/assets/69403301/f55fa03b-ce57-4881-9f5b-5debaf457e25)
![image](https://github.com/Polyfrost/OneConfig/assets/69403301/62e2f9ca-72df-42d3-a220-904e9707f180)
![image](https://github.com/Polyfrost/OneConfig/assets/69403301/e3fa3750-b808-4e3c-a3ab-fc5d97aaf56b)

### Steps to reproduce

press shift

### Expected behavior

too see the config settings

**Comment by nxtdaydelivery** [comment]
turn off antialiasing
