### ISSUE TITLE
OneKeybind NONE

### ISSUE THREAD

**Issue by badjavadev** [Polyfrost/OneConfig#273]
### Bug description

![image](https://github.com/Polyfrost/OneConfig/assets/130553212/bc1a7d3f-9931-4bfe-95dd-394f8f7b3864)
UKeyboard.NONE

![image](https://github.com/Polyfrost/OneConfig/assets/130553212/ee8a7f1c-e892-4fe4-be6a-840811f702e7)
ESC

### Steps to reproduce

is this bug

**Comment by badjavadev** [comment]
UKeyboard.KEY_NONE

**Comment by Wyvest** [comment]
> ### Bug description
> ![image](https://user-images.githubusercontent.com/130553212/251982462-bc1a7d3f-9931-4bfe-95dd-394f8f7b3864.png) UKeyboard.NONE
> 
> ![image](https://user-images.githubusercontent.com/130553212/251982664-ee8a7f1c-e892-4fe4-be6a-840811f702e7.png) ESC
> 
> ### Steps to reproduce
> is this bug
> 
> ### Expected behavior
> _No response_
> 
> ### Anything else?
> _No response_

Right now we just take it from LWJGL iirc, this is a really dumb and small issue so I don't really want to bother fixing this

If you make a PR just making everything upper case or something I'll merge it but lol
