### ISSUE TITLE
Pojav compatibility 

### ISSUE THREAD

**Issue by rohanatt** [Polyfrost/OneConfig#288]
Hi 
it would be nice if we can run oneconfig with open4es since virgl renderer is extremely slow and buggy compared to open4es 

On open4es when a world is joined the whole game crashes

**Comment by alexytomi** [comment]
use zink ffs. virgl is outdated, update your game, open4es is a shader not a renderer

**Comment by pauliesnug** [comment]
We are working on this issue, however it is not our top priority. We are planning to implement PolyUI and attempt to fix this problem after the new UI framework.

**Comment by Wyvest** [comment]
Should be fixed
