### ISSUE TITLE
Trying to use any anti-aliasing on anything breaks the UI

### ISSUE THREAD

**Issue by alexytomi** [Polyfrost/OneConfig#289]
### Category

Interface

### Bug description

Using optifine antialiasing turns everything into a transparent white block and using Nvidia overrides causes everything to be stretched leftwards except for the bottom left section of the screen

### Steps to reproduce

turn on antialiasing

### Anything else?
Heres optifine
https://github.com/Polyfrost/OneConfig/assets/60690056/0b5d6a10-3dc4-43ba-b062-8742d48b5b09

The nVidia control panel antialiasing bug doesn't seem to consistently appear which is odd. I wasn't able to record it sadly

logs showed nothing

**Comment by Sentii** [comment]
Same.
Whole screen turns transparent white when I log on and I get that "OneConfig Hypixel API key" notification in the bottom-right on login. White screen goes away when that notification eventually disappears. Typing "/oneconfig" to open the UI turns the screen solid white until I press escape to exit the OneConfig UI. Disabling OptiFine's AntiAliasing fixes it.

**Comment by Wyvest** [comment]
Should be fixed now!
