### ISSUE TITLE
Hud Border bug

### ISSUE THREAD

**Issue by redefault** [Polyfrost/OneConfig#290]
### Category

HUD

### Bug description

probably renders the border behind the background

![image](https://github.com/Polyfrost/OneConfig/assets/92568191/2d22465e-d182-417c-ade3-6b4a7fd11c13)
![image](https://github.com/Polyfrost/OneConfig/assets/92568191/41d6faf0-9402-45bf-b081-99c93ff00644)

### Steps to reproduce

Forge 1.8.9
Any HUD Mod that utilizes OC with border as an option
Set border color Opacity to like 50%

**Comment by Wyvest** [comment]
Will be added in OneConfig V1, closing as this is a major feature request that is being addressed in other repos
