### ISSUE TITLE
Mods which include Chat Tabs

### ISSUE THREAD

**Issue by ntoukasfz** [Polyfrost/OneConfig#293]
### Category

Mods Which include chat tabs, so i think HUD or Interface dk

### Bug description

So theres these mods for skyblock called Chatting or Skytils, since i started using Oneconfig i cant seem to be able to use the Chat tabs of those mods which i believe may have been caused cause of Oneconfig as they worked completely fine before i started using Oneconfig. (Within SkyClient)

### Steps to reproduce

![modlist](https://github.com/Polyfrost/OneConfig/assets/149107207/2523a162-bb19-46df-a48f-cc44690216e6)
![image](https://github.com/Polyfrost/OneConfig/assets/149107207/484eaa62-4498-4481-8f1f-483983a8808b)

### Anything else?

If theres a possible solution please share it with me or if its not caused by OneConfig.

**Comment by Wyvest** [comment]
> ### Original reporter & ticket id
> _No response_
> 
> ### Category
> Mods Which include chat tabs, so i think HUD or Interface dk
> 
> ### Bug description
> So theres these mods for skyblock called Chatting or Skytils, since i started using Oneconfig i cant seem to be able to use the Chat tabs of those mods which i believe may have been caused cause of Oneconfig as they worked completely fine before i started using Oneconfig. (Within SkyClient)
> 
> ### Steps to reproduce
> ![modlist](https://user-images.githubusercontent.com/149107207/278448403-2523a162-bb19-46df-a48f-cc44690216e6.png) ![image](https://user-images.githubusercontent.com/149107207/278448584-484eaa62-4498-4481-8f1f-483983a8808b.png)
> 
> ### Anything else?
> If theres a possible solution please share it with me or if its not caused by OneConfig.

This is a DG issue - we will fix this eventually. Please report this in the Chatting repo next time!
