### ISSUE TITLE
Potion Effects Hud game crash and visual bugs

### ISSUE THREAD

**Issue by mqtrx** [Polyfrost/OneConfig#303]
### Category

Gameplay and HUD.

### Bug description

Upgrading from older versions of Potion Effects will cause the config to go corrupt due to changes with their Pages either not existing anymore or simply changed.

### Steps to reproduce

Have an old version of the P.E. Hud mod, update OneConfig and P.E. Hud mod to the latest, have P.E. Hud enabled in OneConfig and that's where all the bugs start.

**Comment by pauliesnug** [comment]
Please leave this issue on the original PotionEffects GitHub repository, or make this issue more related to OneConfig (e.g. "Pages don't update after updating a mod, causing a crash")

**Comment by Tellinq** [comment]
This isn’t a potion effects issue. I shouldn’t be held responsible for a config that I do not maintain. I simply update it.

**Comment by Wyvest** [comment]
Will be added in OneConfig V1, closing as this is a major feature request that is being addressed in other repos
