### ISSUE TITLE
Not Building

### ISSUE THREAD

**Issue by FreeMoneyHyb** [Polyfrost/OneConfig#314]
### Original reporter & ticket id

![image](https://github.com/Polyfrost/OneConfig/assets/83422129/b16ab729-5fbc-488a-acd7-9799fffe738a)
whatever org.polyfrost:polyfrost-gradle-toolkit:0.2.9. is its causing errors

### Category

bug

### Bug description

whatever org.polyfrost:polyfrost-gradle-toolkit:0.2.9. is its causing errors

### Steps to reproduce

get intelej and then try to build

**Comment by Wyvest** [comment]
use java 17 instead of java 8. if you need more help, go to discord.gg/polyfrost
