### ISSUE TITLE
If Android is detected, change settings to avoid crash and improve performance

### ISSUE THREAD

**Issue by alexytomi** [Polyfrost/OneConfig#319]
## Is your feature request related to a problem? Please describe
Not really, I just think it'd be easier for users if this was a feature.

## Describe the behaviour you'd like
Add detection for Android. 

If Android is found
 - Set enableBlur to 0 (As it causes a LOT of lag when opening the GUI)
 - Set updatechannel to 1 (As the game crashes without it)
 - I don't know if this part is possible or if it's already implemented but if whatever extensions you guys use to render the GUI is missing, send error saying "Invalid Renderer"

## Describe alternatives you've considered
I don't really see any alternatives to this. It's just setting a config automatically.

## Additional context
The updatechannel option seems to be pretty unknown, hell I just found out about it right now. Would be nice if it was configured automatically.

**Comment by Wyvest** [comment]
Should be fixed now hopefully
