### ISSUE TITLE
Minecraft PolySprint 1.12.2 Doesn't Work

### ISSUE THREAD

**Issue by tdg3001** [Polyfrost/OneConfig#339]
### Category

Gameplay

### Bug description

Toggle Sprint mod 1.12.2 doesn't work. When I press shift, it shows sprinting (toggled), and when I walk, it doesn't automatically sprint.

### Steps to reproduce

SKLauncher Minecraft 1.12.2 Forge 14.23.5.2860
My Mods List: PolySprint, Evergreen Hud, OneConfig, Perspective Mod Redux, Namepain, TimeToLive, Controlling, Keystrokes, BetterFps, Optifine, Collective, StackRefill, MacroKey Binding.

### Anything else?

I tried to join the Discord server, but it doesn't let me join because of the "Unable to Accept Invite" error.

**Comment by ImToggle** [comment]
you should open the issue in PolySprint repo or open a bug report ticket in our discord server, oneconfig itself doesnt cause this issue

**Comment by Mixces** [comment]
Try joining our Discord server again [https://discord.gg/polyfrost](https://discord.gg/polyfrost), and if you do, open a support ticket please.

**Comment by tdg3001** [comment]
i cannot join the discord server



Vào CN, 2 thg 6, 2024 vào lúc 12:13 Mixces ***@***.***> đã
viết:

**Comment by nextdayy** [comment]
moved to PolySprint repo, please use that for tracking this issue instead.
