### ISSUE TITLE
Cannot get MappingsProvider before it has been setup

### ISSUE THREAD

**Issue by Arthur-SKID** [Polyfrost/OneConfig#340]
### Original reporter & ticket id

Build file 'D:\code\OneConfig\versions\build.gradle.kts' line: 11

An exception occurred applying plugin request [id: 'org.polyfrost.multi-version']
> Failed to apply plugin class 'com.replaymod.gradle.preprocess.PreprocessPlugin'.
   > A problem occurred configuring project ':platform:1.8.9-fabric'.
      > Failed to notify project evaluation listener.
         > Failed to setup Minecraft, java.io.UncheckedIOException: Failed to provide intermediate mappings
         > Cannot get MappingsProvider before it has been setup

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

### Category

Set Development Environment

### Bug description

I am unable to successfully build gradle

### Steps to reproduce

I used IDEA

**Comment by nextdayy** [comment]
going to need more of that error please. also, its much easier for us to help if you can contact us on our discord (.gg/polyfrost)

**Comment by Wyvest** [comment]
As nextday said, make a ticket
