### ISSUE TITLE
Can not download or update  one config with cleanroom and java 21,this makes it impossible for me to launch

### ISSUE THREAD

**Issue by mywar5** [Polyfrost/OneConfig#349]
### Category

launch

### Bug description

![Uploading QQ图片20240630183205.png…]()

### Steps to reproduce

mod: polypatch
loader: forge-14.23.5.2860   cleanroom-0.2.2
launcher: hmcl
version:1.12.2

**Comment by Wyvest** [comment]
Will be added in OneConfig V1, closing as this is a major feature request that is being addressed in other repos

**Comment by s0u7a** [comment]
OneConfig v1 when?

**Comment by Wyvest** [comment]
> OneConfig v1 when?

Very early 2025

**Comment by s0u7a** [comment]
At that point, we can finally expect a significant reduction in the weight of our Cleanroom environment. I'm looking forward to it.
