### ISSUE TITLE
Custom bind not working

### ISSUE THREAD

**Issue by S-olp** [Polyfrost/OneConfig#358]
### Category

HUD

### Bug description

Whenever I'm using oneconfig, I try and rebind it from rshift once doing that, it only adds a button to open it not remove rshift

### Steps to reproduce

![image_2024-08-03_122318493](https://github.com/user-attachments/assets/4318979f-b16f-4a0e-a65a-547c06ff4aed)
Try and rebind the gui key, but press rshift after

**Comment by Wyvest** [comment]
Try without Dulkir and Polished GUI. If it still doesn't work, make a ticket at discord.gg/polyfrost
