### ISSUE TITLE
Oneconfig loading essentials too early

### ISSUE THREAD

**Issue by ninjaguardian** [Polyfrost/OneConfig#368]
### Category

Backend (I think?)

### Bug description

I see this one line in my logs:
`Critical problem: mixins.oneconfig.json:VigilantMixin target gg.essential.vigilance.Vigilant was loaded too early.`

### Steps to reproduce

Forge 1.8.9 - 11.15.1.2318
Oneconfig 0.2.2-alpha220
Essentials 1.3.5.5

**Comment by Wyvest** [comment]
this can be ignored
