### ISSUE TITLE
Internal assets not usable

### ISSUE THREAD

**Issue by ForBai** [Polyfrost/OneConfig#66]
### Bug description

When using RenderManager#drawImage or RenderManager#drawSvg you get a compile error that it cant accses "cc.polyfrost.oneconfig.internal.assets.SVGs" / "cc.polyfrost.oneconfig.internal.assets.SVGs"

### Steps to reproduce

Use RenderManager#drawImage or RenderManager#drawSvg

### Expected behavior

No compile error

### Anything else?

here both crash report:
```
/home/lars/MCDevelopment/SkyblockHelper/versions/1.8.9-forge/build/sources/java/cc/polyfrost/example/util/render/graph/Graph.java:67: error: cannot access SVGs
            RenderManager.drawSvg(vg, this.getClass().getResource("/assets/oneconfig/old-icons/ArrowUp.svg").getFile(), X + BORDER + 5, Y +BORDER * 2 +5,20,20,Colorz.WHITE);
                         ^
  class file for cc.polyfrost.oneconfig.internal.assets.SVGs not found
```
and the one with Images
```
/home/lars/MCDevelopment/SkyblockHelper/versions/1.8.9-forge/build/sources/java/cc/polyfrost/example/util/render/graph/Graph.java:67: error: cannot access Images
            RenderManager.drawImage(vg, this.getClass().getResource("/assets/oneconfig/old-icons/ArrowUp.svg").getFile(), X + BORDER + 5, Y +BORDER * 2 +5,20,20,Colorz.WHITE);
                         ^
  class file for cc.polyfrost.oneconfig.internal.assets.Images not found
  ```

**Comment by nxtdaydelivery** [comment]
hi, the SVG and Images classes at the moment are in the internal package, meaning they are excluded from the builds you use. 
They will be moved out eventually, but at the moment they are in there because they change so much during this alpha phase that it is not a good idea to allow them to be public, as any changes can cause crashes.

Sorry for any inconvenience. A bypass may be being added soon to allow you to use them for now.

**Comment by Wyvest** [comment]
To fix this issue (which shouldn't be an issue in the first place lol) RenderManager should stop using these internal classes as constructors. The compiler is failing because it can't figure out what method to use.

**Comment by nxtdaydelivery** [comment]
update oneconfig and will be resolved
